angular.module("MenuApp", ['ui.router'])
// .controller('ItemsController', ItemsController)
// .controller('CategoriesController', CategoriesController)
// .service('MenuDataService', MenuDataService)
// .module('Data', Data)
// .config(RoutesConfig)